workspace:
  base: /go
  path: src/github.com/yukimochi-containers/drone-docker

pipeline:
  build:
    image: golang:1.9
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - go vet ./...
      - go test -cover ./...
      - sh .drone.sh

  publish-amd64:
    image: plugins/docker
    repo: yukimochi/drone-docker
    tags: [ "amd64", "amd64_18.06" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile
    when:
      branch: master
      event: push

  publish-arm:
    image: plugins/docker
    repo: yukimochi/drone-docker
    tags: [ "arm", "arm_18.06" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile.arm
    when:
      branch: master
      event: push

  publish-arm64:
    image: plugins/docker
    repo: yukimochi/drone-docker
    tags: [ "arm64" ,"arm64_18.06" ]
    secrets: [ docker_username, docker_password ]
    dockerfile: docker/Dockerfile.arm64
    when:
      branch: master
      event: push
