# docker build --rm -f docker/Dockerfile -t plugins/docker .

FROM arm64v8/docker:18.06.0-ce-dind

ADD release/linux/arm64/drone-docker /bin/
ENTRYPOINT ["/usr/local/bin/dockerd-entrypoint.sh", "/bin/drone-docker"]
